# Build platform-specific packages and create a GitHub release with artifacts
name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.14'

jobs:
  build-app-packages:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            dist_name: linux
          - os: macos-latest
            dist_name: macos
          - os: windows-latest
            dist_name: windows
      fail-fast: false
    permissions:
      id-token: write
      attestations: write
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Install system dependencies
      - name: Install system packages (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y '^libxcb.*-dev' libarchive-tools libegl-dev libwebp-dev libpng16-16 libx11-xcb-dev rpm
          sudo gem install fpm --bindir /usr/local/bin
      - name: Install system packages (Windows)
        if: startsWith(matrix.os, 'windows')
        run: choco install innosetup -y
      - name: Install system packages (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install create-dmg inih

      # Install dependencies, with caching
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install python + dependencies
        run: |
          uv python install ${{ env.PYTHON_VERSION }}
          uv sync --no-dev

      # Build and test wheel + pyinstaller package
      - name: Build pyinstaller package
        run: |
          uv build --wheel
          just build-pyinstaller
      - name: Rename wheel (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: mv dist/naturtag-*.whl dist/naturtag.whl
      - name: Test pyinstaller package
        run: |
          # Smoke test; any incorrect shared library paths should raise errors here
          BIN=dist/naturtag.app/Contents/MacOS
          if ! test -d "$BIN"; then BIN=dist/naturtag; fi
          QT_QPA_PLATFORM=offscreen $BIN/naturtag --version | grep -q 'naturtag v'
      - name: Attest pyinstaller package
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: naturtag-${{ matrix.dist_name }}.tar.gz

      # Build deb, rpm, pacman, and appimage packages
      - name: Build Linux packages
        if: startsWith(matrix.os, 'ubuntu')
        run: just build-linux-pkgs
      - name: Attest Linux packages
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            dist/naturtag.deb
            dist/naturtag.rpm
            dist/naturtag.pkg.tar.zst
            dist/naturtag.AppImage

      # Build Windows installer with Inno Setup
      - name: Build Windows installer
        if: startsWith(matrix.os, 'windows')
        run: just build-win-installer
      - name: Attest Windows installer
        if: startsWith(matrix.os, 'windows')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/naturtag-installer.exe

      # Build and validate DMG package
      - name: Build disk image (macOS)
        if: startsWith(matrix.os, 'macos')
        run: just build-dmg
      - name: Attest disk image (macOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/naturtag.dmg


      # Upload workflow artifacts
      - name: Upload pyinstaller package
        uses: actions/upload-artifact@v7
        with:
          name: naturtag-${{ matrix.dist_name }}.tar.gz
          path: naturtag-${{ matrix.dist_name }}.tar.gz

      - name: Upload wheel
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v7
        with:
          name: naturtag-python-packages
          path: dist/naturtag.whl

      - name: Upload disk image (macOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v7
        with:
          name: naturtag.dmg
          path: dist/naturtag.dmg

      - name: Upload FPM workflow artifacts (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v7
        with:
          name: naturtag-fpm
          path: |
            dist/naturtag.*
            !dist/naturtag.AppImage

      - name: Upload AppImage (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v7
        with:
          name: naturtag.AppImage
          path: dist/naturtag.AppImage

      - name: Upload Windows installer
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v7
        with:
          name: naturtag-installer.exe
          path: dist/naturtag-installer.exe

  # Create a release with all workflow artifacts attached
  release-app-packages:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-app-packages
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: naturtag*
          path: release-assets
          merge-multiple: true
      - run: ls -l release-assets/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: 'release-assets/naturtag*'
          body: |
            See [installation docs](https://naturtag.readthedocs.io/en/stable/installation.html) for details on the packages below
            See [changelog](https://github.com/pyinat/naturtag/blob/main/HISTORY.md) for release details
            See [milestones](https://github.com/pyinat/naturtag/milestones?state=closed) for completed issues & PRs in this release
          draft: true
