name: Test

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  LATEST_PY_VERSION: '3.14'
  COV_FORMATS: 'term xml'
  PYTEST_VERBOSE: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14', '3.13']
      fail-fast: false

    steps:
      # Install dependencies, with caching
      - uses: actions/checkout@v6
      - uses: extractions/setup-crate@0551596312d4008a6dfbc4d3c38fa20eaef46d2d # v2.0.0
        with:
          repo: casey/just
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install python + dependencies
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync
      - name: Install Qt dependencies
        run: sudo apt-get update && sudo apt-get install -y libegl1

      - name: Run unit tests
        run: just cov xml

      # Upload coverage report to codecov
      - name: 'Upload coverage report to Codecov'
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true

  # Run code analysis checks via pre-commit hooks
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-crate@0551596312d4008a6dfbc4d3c38fa20eaef46d2d # v2.0.0
        with:
          repo: casey/just
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install python + dependencies
        run: |
          uv python install ${{ env.LATEST_PY_VERSION }}
          uv sync --no-dev
      - name: Run style checks & linting
        uses: j178/prek-action@79f765515bd648eb4d6bb1b17277b7cb22cb6468 # v2.0.0

      - name: Scan dependencies for known vulnerabilities
        run: just audit
